version: "2"

services:
  app:
    links:
      - database
    environment:
      - TELEGRAM_APIKEY=${TELEGRAM_APIKEY}
    build: .
    command: go run main.go
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./database/postgresql:/etc/postgresql"
      - "./database/log:/var/log/postgresql"
      - "./database/postgresqlData/data:/var/lib/postgresql/data"
